# Generated by Django 3.0.3 on 2020-03-25 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager_userdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='thread_deleterequestdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_threadid', models.IntegerField()),
                ('reason_delete', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='threadcontent_deleterequestdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_contentid', models.IntegerField()),
                ('reason_delete', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Threaddb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastdate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='threadcontentdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('threadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Threaddb')),
            ],
        ),
    ]
